:host: 0.0.0.0
:port: 4567
:databases_widget: tree
:options:
  :blastn:
    :default:
      :description: "Standard nucleotide BLAST (E-value: 1e-5, Max hits: 100)"
      :attributes:
        - "-task blastn"
        - "-evalue 1e-5"
        - "-max_target_seqs 100"
    :short-seq:
      :description: "Short sequences under 50bp (E-value: 0.1)"
      :attributes:
        - "-task blastn-short"
        - "-evalue 1e-1"
  :blastp:
    :default:
      :description: "Standard protein BLAST (E-value: 1e-5, Max hits: 100)"
      :attributes:
        - "-evalue 1e-5"
        - "-max_target_seqs 100"
  :blastx:
    :default:
      :description: "Translated nucleotide vs protein (E-value: 1e-5, Max hits: 100)"
      :attributes:
        - "-evalue 1e-5"
        - "-max_target_seqs 100"
  :tblastx:
    :default:
      :description: "Translated nucleotide vs translated nucleotide (E-value: 1e-5, Max hits: 100)"
      :attributes:
        - "-evalue 1e-5"
        - "-max_target_seqs 100"
  :tblastn:
    :default:
      :description: "Protein vs translated nucleotide (E-value: 1e-5, Max hits: 100)"
      :attributes:
        - "-evalue 1e-5"
        - "-max_target_seqs 100"
:num_threads: 1
:num_jobs: 1
:job_lifetime: 43200
:database_dir: "/db"
