version: "3.5"
services:
  wb:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${WB_IMAGE}
    command: ["sequenceserver", "-c", "conf/sequenceserver.wormbase.conf"]
    volumes:
      - ./db/wormbase:/db
    ports:
      - "5001:4567"
  fb:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${FB_IMAGE}
    command: ["sequenceserver", "-c", "conf/sequenceserver.flybase.conf"]
    volumes:
      - ./db/flybase:/db
    ports:
      - "5002:4567"
  sgd:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${SGD_IMAGE}
    command: ["sequenceserver", "-c", "conf/sequenceserver.sgd.conf"]
    volumes:
      - ./db/sgd:/db
    ports:
      - "5003:4567"
  xenbase:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${XB_IMAGE}
    command: ["sequenceserver", "-c", "conf/sequenceserver.xenbase.conf"]
    volumes:
      - ./db/xenbase:/db
    ports:
      - "5004:4567"
