version: "3.5"
services:
  wb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db/wormbase:/db
      - ./conf/sequenceserver.wormbase.conf:/root/.sequenceserver.conf
    ports:
      - "5001:4567"
  fb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db/flybase:/db
      - ./conf/sequenceserver.flybase.conf:/root/.sequenceserver.conf
    ports:
      - "5002:4567"
  sgd:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db/sgd:/db
      - ./conf/sequenceserver.sgd.conf:/root/.sequenceserver.conf
    ports:
      - "5003:4567"
